name: New device compatibility
description: Add a new device on the compatibility list
title: "[Device] "
type: device
body:
  - type: input
    id: manufacturer
    attributes:
      label: Device manufacturer
      placeholder: Manufacturer
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Model
    validations:
      required: true
  - type: input
    id: image
    attribues:
      label: Image link
      description: Link to a picture of this device
  - type: dropdown
    id: compatibility
    attributes:
      label: Compatibility
      description: Is this device compatible with Versatile Thermostat?
      options:
        - Compatible
        - Not compatible
        - Partially compatible
      default: 1
    validations:
      required: true
    - type: textarea
      id: config
      attributes:
        label: Device configuration
        description: Your YAML configuration for this device
        render: JSON
    - type: textarea
      id: description
      attributes:
        label: Additional informations
        description: If you want to give us any additional information about this device.
        render: Markdown
